### ISSUE TITLE
Bot stopped working. 

### ISSUE THREAD

**Issue by TaboliA** [Veeenz/webp-to-png-converter-bot#2]
a few days ago bot stopped working.
Thanks for the Bot anyway :)

**Comment by Veeenz** [comment]
Hello TaboliA,
thanks for the feedback. The server has been restarted and I didn't notice it.
The bot is up again. 

If you need a feature for the bot, tell me.

**Comment by TaboliA** [comment]
Thanks! bot it up and running again!

**Comment by TaboliA** [comment]
lately not working  again ..

**Comment by TaboliA** [comment]
not working on my end...
